# Default values for shopping-microservices.

imageRegistry: ghcr.io/pkrishn1-pk/shopping-microservices
mysql:
  rootPassword: root
  storageSize: 1Gi

# List of microservices to deploy
apps:
  cart:
    name: cart-service
    port: 8081
    dbName: shopping_cart_db
    imageTag: sha-dc1ddfe05cb1ca4e2ac813fd0b41f3bb202a3dca
  inventory:
    name: inventory-service
    port: 8083
    dbName: shopping_inventory_db
    imageTag: sha-dc1ddfe05cb1ca4e2ac813fd0b41f3bb202a3dca
  order:
    name: order-service
    port: 8082
    dbName: shopping_order_db
    imageTag: sha-dc1ddfe05cb1ca4e2ac813fd0b41f3bb202a3dca
